server.port: 8087

spring:
  cloud.gateway:
    discovery.locator.enabled: true
    routes:
      - id: view-service
#        uri: lb://view
        uri: http://localhost:8088
        predicates:
          - Path=/view/**
        filters:
          - RewritePath=/view/(?<path>.*), /$\{path}
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
          - Path=/v3/api-docs/**
        filters:
          - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

springdoc:
  version: '@springdoc.version@'
