server.port: 8087

spring:
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/auth/realms/hcbox  # local, /etc/hosts 수정
#            user-name-attribute: preferred_username
#        registration:
#          keycloak:
#            client-id: hcbox-swagger
#            client-secret: ASwgacXeGIVln2ksmOaPIH5jzPTABUmJ
  cloud.gateway:
    discovery.locator.enabled: true
    routes:
      - id: views-service
        uri: http://localhost:8088
        predicates:
          - Path=/views/**
      - id: orders-service
        uri: http://localhost:9090
        predicates:
          - Path=/orders/**
      - id: products-service
        uri: http://localhost:9091
        predicates:
          - Path=/products/**
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
          - Path=/v3/api-docs/**
        filters:
          - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

springdoc:
  version: '@springdoc.version@'
logging:
  config: config-repo/logback.xml
