server:
  port: 9090

spring:
  config:
    activate:
      on-profile: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  cloud:
    function:
      definition: orderConsumer; # 함수 이름
    stream:
      default:
        consumer:
          useNativeEncoding: on
        contentType: application/*+avro

      bindings:
        order-in-0:
          destination: hcbox.order.0
          group: orderGroup-1
          content-type: application/*+avro
          consumer.configuration:
            key.deserializer: org.apache.kafka.common.serialization.StringSerializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
#            schema.registry.url: some.registry.io

      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          configuration:
            acks: all

  datasource:
    initialize: true
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
