server:
  port: 9090

spring:
  config:
    activate:
      on-profile: h2
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  datasource:
    initialize: true
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
