app:
  order:
    baseUrl: "http://localhost:9090"
  product:
    baseUrl: "http://localhost:9091"

server:
  port: 8088

spring:
  config:
    activate:
      on-profile: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  cloud:
    stream:
      bindings:
        orderEventProcessor-out-0:
          destination: order-events-v1
          content-type: application/*+avro
          producer:
            client-id: view
            use-native-encoding: true
            configuration:
              key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
              value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

      kafka.binder:
        brokers: 127.0.0.1
        defaultBrokerPort: 9092
        configuration:
          acks: all
        auto-add-partitions: true

spring.kafka:
  properties:
    schema.registry.url: http://localhost:8081
  producer:
    key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

  datasource:
    initialize: true
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
